services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_net

  app:
    build: "."
    restart: always
    ports:
      - "6565:6565"
    environment:
      GIN_MODE: debug
      BIND_IP: "0.0.0.0"
    depends_on:
      - mongo
      - redis
      - consul
    networks:
      - app_net

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  consul:
    image: hashicorp/consul:1.17
    restart: always
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - app_net

volumes:
  mongo_data:

networks:
  app_net:
    driver: bridge
