version: "3.5"

services:
  app:
    build: "."
    restart: always
    ports:
      - "6565:6565"
    volumes:
      - "/Users/ty/server/Twitta/configs:/configs"
      # - "/Users/ty/Twitta/logs:/logs"
      # 挂载证书
      - "/Users/ty/server/Twitta/certs:/etc/ssl/certs/"
    depends_on:
      - mongo
      - redis
      - minio
      - zinc
#      - consul
    networks:
      - app_net

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/Users/ty/mongo/mongo_data:/data/db"
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    restart: always
    container_name: minio
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "/Users/ty/minio/data1:/data1"
      - "/Users/ty/minio/data2:/data2"
    networks:
      - app_net

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    restart: always
    container_name: zinc
    environment:
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "Complexpass#123"
    ports:
      - "4080:4080"
    volumes:
      - "/Users/ty/zinc/data:/data"
    networks:
      - app_net
# consul容器跟随服务创建，所以这里注释掉了
#  consul:
#    image: consul:latest
#    container_name: consul
#    ports:
#      - "8500:8500"
#    networks:
#      - app_net

networks:
  app_net:
    external: true