version: "1.0.1"
debug_mode: "debug"
addr: ":6565"
time_location: "Asia/Chongqing"
prometheus_enable: false

mongo:
  hosts:
    - "127.0.0.1:27017"
  auth_source: ""
  username: ""
  password: ""
  timeout: 30

redis:
  addr: "127.0.0.1:6379"

minio:
  end_point: "127.0.0.1:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  user_ssl: false

jwt:
  key: "ajgiengijheiganege"
  duration: 2678400

email:
  host: "smtp.163.com"
  port: 25
  # 此密码为开启smtp/pop3的授权码,非真实邮箱密码
  password: "CCRGOOJZTIBWQASI"
  send_person_name: "Twitta"
  send_person_addr: "tianyuanyuans@163.com"

zinc:
  username: "admin"
  password: "Complexpass#123"

kafka:
  consumer:
    addrs:
      - "127.0.0.1:9093"
    topics:
      - "email"
  producer:
    addrs:
      - "127.0.0.1:9093"
    topics:
      - "email"

consul:
  host: "127.0.0.1"
  port: "8500"

user:
  name: "user"
