name: "twitta"
debug_mode: "debug"
port: 6565
time_location: "Asia/Shanghai"
prometheus_enable: true
config_path: api/twitta

mongo:
  hosts:
    - "localhost:27017"
  auth_source: ""
  username: ""
  password: ""
  timeout: 30

redis:
  addr: "localhost:6379"

jwt:
  key: "ajgiengijheiganege"
  duration: 2678400

#kafka:
#  consumer:
#    addrs:
#      - "127.0.0.1:9093"
#    topics:
#      - "email"
#  producer:
#    addrs:
#      - "127.0.0.1:9093"
#    topics:
#      - "email"

consul:
  host: "localhost"
  port: "8500"

static-oss:
  domain: "http://127.0.0.1:9000"

push:
  name: "push_service"

oss:
  name: "oss_service"

es:
  name: "es_service"

face_recognition:
  name: "face_recognition_service"