name: "twitta"
#mode: "debug" 此参数通过设置环境变量GIN_MODE="value" GIN自动读取并设置
port: 6565
time_location: "Asia/Shanghai"
prometheus_enable: true
config_path: api/twitta

#consul:
#  host: "localhost"
#  port: "8500"

mongo:
  hosts:
    - "localhost:27017"
  auth_source: ""
  username: ""
  password: ""
  db: "twitta"
  timeout: 30

redis:
  addr: "localhost:6379"

jwt:
  key: "ajgiengijheiganege"
  duration: 2678400

static-oss:
  domain: "http://127.0.0.1:9000"

push:
  name: "push_service"

oss:
  name: "oss_service"

es:
  name: "es_service"

face_recognition:
  name: "face_recognition_service"
